data:
  source: openml
  dataset_id: 42585
  target: class
drop_columns:  []
preprocessing:
  fill_strategy:
    sex: most_frequent
    island: most_frequent
    culmen_length_mm: median
    culmen_depth_mm: median
    flipper_length_mm: median
    body_mass_g: median  
    
  encode:
    sex:
      male: 0
      female: 1
    species:
      Adelie: 0
      Chinstrap: 1
      Gentoo: 2
    island:
      Biscoe: 0
      Dream: 1
      Torgersen: 2
    embarked: onehot
 
model:
  type: RandomForestClassifier 
  parameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42
training:
  test_size: 0.2 
  random_state: 42
  